---
helmDefaults:
  atomic: true
  wait: true
  verify: true

  # ---------------------  IMPORTANT ---------------------------
  # Uncomment the paths below for the applications that you'd like to manage.
  # By default all the helmfiles have `install:true`. So if you uncomment one of these
  # helmfiles, the associated application will be tried to be installed or updated.
  #
  # You can set `install:false` to either uninstall the app from your cluster, or
  # keep it uninstalled if you don't have it already installed.
  #
  # For more information, reference the Helmfile repository at:
  # https://github.com/helmfile/helmfile
  # ------------------------------------------------------------
helmfiles:
- path: commons/repositories.yaml
- path: applications/services_admin/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}
- path: applications/services_1/whoami/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}
#
missingFileHandler: Warn
  #
# environment file
#
#environments:
#  default:
#    values:
#    - env/default.yaml
#  dev:
#    values:
#    - env/default.yaml
#    - env/{{ .Environment.Name }}.yaml
##  stage:
##    values:
##    - env/default.yaml
##    - env/{{ .Environment.Name }}.yaml
##  prod:
##    values:
###    values:
##    - env/default.yaml
##    - env/{{ .Environment.Name }}.yaml
