---
helmDefaults:
  atomic: true
  wait: true
  verify: true

helmfiles:
- path: commons/repositories.yaml
- path: applications/services_admin/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}
missingFileHandler: Warn
