apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  version: v4.9.0
  set:
  valuesContent: |-
    fullnameOverride: ingress-nginx
    controller:
      kind: DaemonSet
      daemonset:
        useHostNetwork: true
        useHostPort: true
      hostPort:
        enabled: true
      service:
        enabled: true
        type: NodePort
      dnsPolicy: ClusterFirstWithHostNet
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
      nodeSelector:
        ingress: "true"
      config:
        use-forwarded-headers: "true"
