---
bases:
- environments.yaml
---
repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

releases:
- name: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: {{ .Values.ingress_nginx.chart_version | quote }}
  namespace: {{ .Values.ingress_nginx.ingress_namespace }}
  createNamespace: true
  installed: {{ .Values.ingress_nginx.installed }}
  values:
    # default values for helm chart
    # # templated gotmpl values would also inherit the values
    - values.yaml.gotmpl
