---
#ingress_nginx: {}
ingress_nginx:
#  installed: false
  node_selector:
    ingress: "true"
ingress_nginx_admin:
  #installed: false
  node_selector:
    web: "true"

loki:
#  installed: false
  node_selector:
    ingress: "true"

prometheus:
  #  installed: false
  node_selector:
    ingress: "true"

#whoami:
#  installed: true
